name: Execute Shell

on: push
jobs:
    execute_shell_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4
        - name: List Repo File
          run: ls -ltra
        - name: Execute Shell Script
          run: |
            chmod +x ascii-scripts.sh
            ./ascii-scripts.sh