name: My Workflow

on: push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo
          uses: actions/checkout@v4
        
        - name: List and Reaad File
          run: | 
            echo "My Github Actions"
            ls -ltrs
            cat README.md
        - name: Generate ASCII Artwork
          run: cowsay -f dragon "Run for cover, I am a Drago....RAWR" >> dragon.txt
      
    
      
         # - name: List Files
         #   run: ls
         #- name: read Files
         #  run: cat README.md